version: "3"
services:
  mysql-standalone:
    image: mysql:5.7
    hostname: mysql-standalone
    restart: always
    healthcheck:
      test: sleep 1
      timeout: 2s
      start_period: 1s
    environment:
      MYSQL_DATABASE: banco_usuario
      MYSQL_USER: teste
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: teste
    
    ports:
      - "3307:3306"

    networks:
      - common-network 

  projetobasico:
    image: projetobasico:latest
    restart: always
    depends_on: 
      mysql-standalone:
        condition: service_healthy
    ports:
      - "8081:8080"

    
    networks:
      - common-network

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/banco_usuario?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: teste
      SPRING_DATASOURCE_PASSWORD: 123
    
    build: 
      context: .
      dockerfile: Dockerfile

networks:
  common-network:
    driver: bridge